// IRONLOG/api/utils/prestartPortuguese.js — Portuguese (Mozambique) wording for
// the machine pre-start checklists. Checks are stored and reported in English;
// operators can read and answer them in Portuguese. test/prestartPortuguese.test.js
// fails when a template line has no translation here.

export const PRESTART_PT = {
  // Template titles
  "Excavator pre-start": "Pré-arranque da escavadora",
  "Dozer pre-start": "Pré-arranque do buldózer",
  "Wheel loader pre-start": "Pré-arranque da pá carregadora",
  "Haul truck pre-start": "Pré-arranque do dumper",
  "Tipper truck pre-start": "Pré-arranque do camião basculante",
  "Water truck pre-start": "Pré-arranque do camião cisterna de água",
  "Fuel truck pre-start": "Pré-arranque do camião de combustível",
  "Grader pre-start": "Pré-arranque da motoniveladora",
  "Mobile crane pre-start": "Pré-arranque da grua móvel",
  "Mobile crusher pre-start": "Pré-arranque do britador móvel",
  "Mobile screen pre-start": "Pré-arranque do crivo móvel",
  "Generator pre-start": "Pré-arranque do gerador",
  "Backhoe / loader pre-start": "Pré-arranque da retroescavadora",

  // Section titles
  "Fluid levels": "Níveis de fluidos",
  "Undercarriage": "Trem de rodagem / esteiras",
  "Safety & cab": "Segurança e cabine",
  "Safety": "Segurança",
  "Machine & tyres": "Máquina e pneus",
  "Body & running gear": "Caixa basculante e rodagem",
  "Truck & tipper body": "Camião e caixa basculante",
  "Water tank & sprays": "Tanque de água e aspersores",
  "Fluids & fuel systems": "Fluidos e sistemas de combustível",
  "Dispensing equipment": "Equipamento de abastecimento",
  "Vehicle": "Veículo",
  "Moldboard & tyres": "Lâmina e pneus",
  "Crane & carrier": "Grua e chassis",
  "Crushing plant": "Instalação de britagem",
  "Tracks / undercarriage": "Esteiras / trem de rodagem",
  "Screening plant": "Instalação de crivagem",
  "Fluids & fuel": "Fluidos e combustível",
  "Electrical & connections": "Elétrica e ligações",
  "Operation": "Funcionamento",
  "Machine & attachments": "Máquina e acessórios",

  // Checks
  "Engine oil level OK": "Nível de óleo do motor OK",
  "Engine oil OK": "Óleo do motor OK",
  "Coolant level OK": "Nível do líquido de arrefecimento OK",
  "Coolant OK": "Líquido de arrefecimento OK",
  "Hydraulic oil level OK": "Nível de óleo hidráulico OK",
  "Hydraulic oil OK": "Óleo hidráulico OK",
  "Hydraulic oil OK (if applicable)": "Óleo hidráulico OK (se aplicável)",
  "Tipper hydraulic oil OK": "Óleo hidráulico do basculante OK",
  "Hydraulic / transmission oil OK": "Óleo hidráulico / da transmissão OK",
  "Swing / slew gear oil OK (if applicable)": "Óleo da giratória OK (se aplicável)",
  "Final drives / track gear oil OK": "Redutores finais / óleo das esteiras OK",
  "Final drives OK": "Redutores finais OK",
  "Transmission / axle oils OK": "Óleos da transmissão / eixos OK",
  "Brake fluid OK": "Líquido dos travões OK",
  "Circle drive oil OK (if applicable)": "Óleo do círculo OK (se aplicável)",
  "Track tension OK": "Tensão das esteiras OK",
  "Rollers & idlers OK (no seized / flat spots)": "Rolos e rodas guia OK (sem bloqueios / partes planas)",
  "Rollers & idlers OK": "Rolos e rodas guia OK",
  "Rollers & sprocket OK": "Rolos e roda motriz OK",
  "Sprocket teeth OK": "Dentes da roda motriz OK",
  "No abnormal cuts, cracks, or leaks on tracks": "Sem cortes, fissuras ou fugas anormais nas esteiras",
  "Fire extinguisher present & charged": "Extintor presente e carregado",
  "Fire extinguisher OK": "Extintor OK",
  "Seat belt OK": "Cinto de segurança OK",
  "Mirrors / cameras clean & working": "Espelhos / câmaras limpos e a funcionar",
  "Mirrors clean & intact": "Espelhos limpos e intactos",
  "Horn & emergency stop OK": "Buzina e paragem de emergência OK",
  "Horn & E-stop OK": "Buzina e paragem de emergência OK",
  "Horn OK": "Buzina OK",
  "Horn & reversing alarm OK": "Buzina e alarme de marcha-atrás OK",
  "Emergency stop OK": "Paragem de emergência OK",
  "Windows / guards intact": "Janelas / proteções intactas",
  "Guards & covers in place": "Proteções e tampas no lugar",
  "Blade / ripper pins & hydraulics OK": "Pinos da lâmina / ripper e hidráulica OK",
  "Tyres — pressure & damage OK": "Pneus — pressão e danos OK",
  "Tyres OK": "Pneus OK",
  "Carrier tyres OK": "Pneus do chassis OK",
  "Wheel nuts tight (no missing nuts)": "Porcas das rodas apertadas (nenhuma em falta)",
  "Centre articulation / pins OK": "Articulação central / pinos OK",
  "Steering & articulation OK": "Direção e articulação OK",
  "Steering free play OK": "Folga da direção OK",
  "Brakes OK": "Travões OK",
  "Brakes & steering OK": "Travões e direção OK",
  "Brakes & air pressure OK": "Travões e pressão de ar OK",
  "Bucket & linkage OK": "Balde e articulações OK",
  "Loader bucket & linkage OK": "Balde da pá e articulações OK",
  "Backhoe arm, pins & bucket OK": "Braço, pinos e balde da retro OK",
  "Moldboard & linkage OK": "Lâmina e articulações OK",
  "Lights & beacon OK": "Luzes e pirilampo OK",
  "Lights, indicators & beacon OK": "Luzes, piscas e pirilampo OK",
  "Body / hoist & tail door OK": "Caixa, cilindro de elevação e porta traseira OK",
  "Tipper body, ram & tailgate OK": "Caixa basculante, cilindro e taipal traseiro OK",
  "PTO & tipping controls OK": "Tomada de força e comandos do basculante OK",
  "No fuel, oil, or air leaks": "Sem fugas de combustível, óleo ou ar",
  "No fuel, oil, or hydraulic leaks": "Sem fugas de combustível, óleo ou hidráulica",
  "No fuel or oil leaks": "Sem fugas de combustível ou óleo",
  "No abnormal leaks, cracks, or damage": "Sem fugas, fissuras ou danos anormais",
  "No abnormal leaks or damage": "Sem fugas ou danos anormais",
  "Water tank & mountings OK (no leaks or cracks)": "Tanque de água e fixações OK (sem fugas ou fissuras)",
  "Water pump & drive OK": "Bomba de água e acionamento OK",
  "Spray bars & nozzles OK (not blocked)": "Barras e bicos de aspersão OK (não entupidos)",
  "Water hoses & valves OK": "Mangueiras e válvulas de água OK",
  "Product tank level OK": "Nível do tanque de produto OK",
  "Fuel tank level OK": "Nível do tanque de combustível OK",
  "Hoses, reels & nozzles OK (no damage/leaks)": "Mangueiras, carretéis e bicos OK (sem danos/fugas)",
  "Meters / pumps OK": "Contadores / bombas OK",
  "Bonding & earthing OK": "Ligação equipotencial e terra OK",
  "Earthing / bonding OK": "Terra / ligação equipotencial OK",
  "Spill kit present & accessible": "Kit de derrames presente e acessível",
  "Hazchem / no smoking signage OK": "Sinalização de perigo / proibido fumar OK",
  "Outriggers / pads OK": "Estabilizadores / sapatas OK",
  "Wire rope / hook block OK": "Cabo de aço / moitão do gancho OK",
  "Load chart / duty indicator accessible": "Tabela de cargas / indicador de carga acessível",
  "Auto / manual grease system OK": "Sistema de lubrificação automático / manual OK",
  "Feed hopper, grizzly & feeder OK": "Tremonha, grelha e alimentador OK",
  "Jaw / cone liner & chamber OK (no loose parts)": "Mandíbulas / revestimento do cone e câmara OK (sem peças soltas)",
  "Discharge conveyor, belt & scrapers OK": "Tapete de descarga, correia e raspadores OK",
  "Discharge conveyors & belts OK": "Tapetes e correias de descarga OK",
  "Dust suppression / water spray OK": "Supressão de poeira / aspersão de água OK",
  "Screen panels / mesh & tension OK": "Painéis / malha do crivo e tensão OK",
  "Feed conveyor & chutes OK": "Tapete de alimentação e calhas OK",
  "Springs, mounts & vibration unit OK": "Molas, apoios e unidade vibratória OK",
  "Power cables & plugs OK (no damage)": "Cabos de energia e fichas OK (sem danos)",
  "Distribution panel & breakers OK": "Quadro de distribuição e disjuntores OK",
  "Auto-start / control panel OK (if fitted)": "Arranque automático / painel de controlo OK (se existir)",
  "Exhaust & ventilation clear": "Escape e ventilação desobstruídos",
  "Battery & charging OK": "Bateria e carregamento OK",
  "Brief run / load test OK (no abnormal noise or smoke)": "Teste curto / de carga OK (sem ruído ou fumo anormal)",
  "Warning signage visible": "Sinalização de aviso visível",
};

export function toPortuguese(text) {
  return PRESTART_PT[String(text || "")] || "";
}

/** Copy of a template with title_pt / label_pt next to the English wording. */
export function withPortuguese(template) {
  if (!template) return template;
  return {
    ...template,
    title_pt: toPortuguese(template.title),
    sections: (template.sections || []).map((sec) => ({
      ...sec,
      title_pt: toPortuguese(sec.title),
      items: (sec.items || []).map((it) => ({ ...it, label_pt: toPortuguese(it.label) })),
    })),
  };
}
